import type {
  ActivityRecord,
  DashboardSnapshot,
  DocumentRecord,
  GraduateRecord,
  LeadershipRecord,
  Member,
  NotificationRecord,
  UserProfile,
} from "@/types/domain";

const now = new Date().toISOString();

export const demoUser: UserProfile = {
  id: "demo-user-1",
  email: "admin@ssfi.org",
  display_name: "SSFI Demo Admin",
  role: "super_admin",
  role_label: "Super Admin",
  member_id: "member-001",
};

export const mockMembers: Member[] = [
  {
    id: "member-001",
    profile_image: null,
    full_name: "Esther Hlyan",
    gender: "Female",
    date_of_birth: "1998-08-12",
    phone_number: "+919876543210",
    email: "esther@ssfi.org",
    whatsapp: "+919876543210",
    telegram: "estherhlyan",
    village_in_myanmar: "Tedim",
    current_city_in_india: "Bengaluru",
    state_in_india: "Karnataka",
    university: "Christ University",
    major: "Data Science",
    batch: "2020",
    year_joined: 2020,
    current_position: "President",
    bio: "Focused on alumni systems, organizational continuity, and member wellbeing.",
    status: "active",
    created_at: now,
    updated_at: now,
  },
  {
    id: "member-002",
    profile_image: null,
    full_name: "Mang Pau",
    gender: "Male",
    date_of_birth: "1999-04-04",
    phone_number: "+919812341234",
    email: "mang@ssfi.org",
    whatsapp: "+919812341234",
    telegram: "mangpau",
    village_in_myanmar: "Kalemyo",
    current_city_in_india: "Pune",
    state_in_india: "Maharashtra",
    university: "Savitribai Phule Pune University",
    major: "Mechanical Engineering",
    batch: "2019",
    year_joined: 2019,
    current_position: "General Secretary",
    bio: "Coordinates operational records and executive planning.",
    status: "active",
    created_at: now,
    updated_at: now,
  },
  {
    id: "member-003",
    profile_image: null,
    full_name: "Ngaih Lun",
    gender: "Male",
    date_of_birth: "1997-02-18",
    phone_number: "+918801122334",
    email: "lun@ssfi.org",
    whatsapp: "+918801122334",
    telegram: "ngaihlun",
    village_in_myanmar: "Hakha",
    current_city_in_india: "Delhi",
    state_in_india: "Delhi",
    university: "University of Delhi",
    major: "Economics",
    batch: "2018",
    year_joined: 2018,
    current_position: "Alumni Coordinator",
    bio: "Supports transitions from active membership into alumni engagement.",
    status: "alumni",
    created_at: now,
    updated_at: now,
  },
  {
    id: "member-004",
    profile_image: null,
    full_name: "Mary Cin",
    gender: "Female",
    date_of_birth: "2001-06-03",
    phone_number: "+917701112233",
    email: "mary@ssfi.org",
    whatsapp: "+917701112233",
    telegram: "marycin",
    village_in_myanmar: "Falam",
    current_city_in_india: "Hyderabad",
    state_in_india: "Telangana",
    university: "University of Hyderabad",
    major: "Political Science",
    batch: "2022",
    year_joined: 2022,
    current_position: "Member",
    bio: "Researches student policy and event coordination.",
    status: "active",
    created_at: now,
    updated_at: now,
  },
];

export const mockLeadershipRecords: LeadershipRecord[] = [
  {
    id: "leader-001",
    member_id: "member-001",
    leadership_position: "President",
    term_start: "2025-01-01",
    term_end: null,
    description: "Leading digital modernization and organizational data stewardship.",
    created_at: now,
    member: mockMembers[0],
  },
  {
    id: "leader-002",
    member_id: "member-002",
    leadership_position: "General Secretary",
    term_start: "2025-01-01",
    term_end: null,
    description: "Manages records, governance, and executive operations.",
    created_at: now,
    member: mockMembers[1],
  },
  {
    id: "leader-003",
    member_id: "member-003",
    leadership_position: "Alumni Coordinator",
    term_start: "2023-01-01",
    term_end: "2024-12-31",
    description: "Established the first graduate follow-up workflow.",
    created_at: now,
    member: mockMembers[2],
  },
];

export const mockGraduates: GraduateRecord[] = [
  {
    id: "graduate-001",
    member_id: "member-003",
    degree: "BA Economics",
    graduation_date: "2021-06-01",
    graduation_year: 2021,
    university: "University of Delhi",
    current_job: "Research Associate",
    current_country: "India",
    current_city: "Delhi",
    company: "Youth Policy Lab",
    linkedin_url: "https://www.linkedin.com/in/ngaih-lun",
    created_at: now,
    updated_at: now,
    member: mockMembers[2],
  },
];

export const mockDocuments: DocumentRecord[] = [
  {
    id: "document-001",
    title: "SSFI Constitution 2025",
    description: "Latest approved constitutional document for organization governance.",
    category: "constitution",
    file_path: "constitution/ssfi-constitution-2025.pdf",
    file_name: "ssfi-constitution-2025.pdf",
    file_size: 824313,
    mime_type: "application/pdf",
    uploaded_by: demoUser.id,
    created_at: now,
  },
  {
    id: "document-002",
    title: "Annual Report 2024",
    description: "Year-end summary of member growth, activities, and outcomes.",
    category: "reports",
    file_path: "reports/annual-report-2024.pdf",
    file_name: "annual-report-2024.pdf",
    file_size: 1210312,
    mime_type: "application/pdf",
    uploaded_by: demoUser.id,
    created_at: now,
  },
];

export const mockActivities: ActivityRecord[] = [
  {
    id: "activity-001",
    actor_user_id: demoUser.id,
    action: "member.created",
    entity_type: "member",
    entity_id: "member-004",
    metadata: { source: "demo" },
    created_at: now,
  },
  {
    id: "activity-002",
    actor_user_id: demoUser.id,
    action: "document.uploaded",
    entity_type: "document",
    entity_id: "document-001",
    metadata: { source: "demo" },
    created_at: now,
  },
];

export const mockNotifications: NotificationRecord[] = [
  {
    id: "notification-001",
    user_id: demoUser.id,
    title: "Supabase not connected",
    body: "You are viewing demo data until environment variables are configured.",
    href: "/dashboard",
    read_at: null,
    created_at: now,
  },
];

export const mockDashboardSnapshot: DashboardSnapshot = {
  metrics: [
    { label: "Total members", value: 124, helper: "12 joined this quarter", trend: 9 },
    { label: "Total alumni", value: 36, helper: "7 new graduate records", trend: 5 },
    { label: "Active leaders", value: 8, helper: "Current term 2025-2026", trend: 0 },
    { label: "Documents", value: 18, helper: "Governance and reports", trend: 3 },
  ],
  membersByState: [
    { label: "Karnataka", value: 34 },
    { label: "Maharashtra", value: 26 },
    { label: "Delhi", value: 18 },
    { label: "Telangana", value: 11 },
  ],
  membersByUniversity: [
    { label: "Christ University", value: 16 },
    { label: "Delhi University", value: 12 },
    { label: "UoH", value: 8 },
    { label: "SPPU", value: 7 },
  ],
  membersByMajor: [
    { label: "Data Science", value: 12 },
    { label: "Economics", value: 10 },
    { label: "Engineering", value: 18 },
    { label: "Political Science", value: 6 },
  ],
  graduationStats: [
    { label: "2021", value: 7 },
    { label: "2022", value: 9 },
    { label: "2023", value: 11 },
    { label: "2024", value: 8 },
  ],
  activeLeaders: mockLeadershipRecords.filter((record) => !record.term_end),
  recentMembers: mockMembers,
  recentDocuments: mockDocuments,
};
